"""The gate judges content, not the path it arrived on.

SIDRA quarantines roughly a tenth of its own repository: the detectors, the
envelope and their tests legitimately contain injection strings and synthetic
credentials, because that is what a detector's source code *is*. The obvious
relief - exempt ``src/sidra_ai/security/**`` - is refused, and these tests
pin the refusal so it survives a future well-meaning "fix".

Why it is refused: ``path`` is attacker-controlled provenance. The audit
boundary already drops it for exactly that reason (SECURITY.md gap 6). An
exemption keyed on a field we classify as untrusted is a hole shaped like a
path - any document that claims the right path gets an unscreened channel
into the index, and paths are not unique across the five allowlisted
repositories.

The supported route is per-version quarantine release. See
``docs/SECURITY.md`` gap 10 for the decision and its cost.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

from sidra_ai.documents import Document, Provenance, SourceType, TrustLevel
from sidra_ai.security.decisions import Decision
from sidra_ai.security.gate import SecurityGate

REPOSITORY = "tukemen-rgb/sidra-ai"

# Credential-shaped test values are generated by repetition, never written
# out, so that the repository never carries a value that looks live.
FAKE_GITHUB_TOKEN = "ghp_" + "2" * 36

#: Content of the kind that quarantines this repository's own source: a
#: detector's pattern table and a test's fixture, side by side.
SELF_SECURITY_SOURCE = (
    'OVERRIDE = re.compile(r"ignore all previous instructions")\n'
    f'FAKE_TOKEN = "{FAKE_GITHUB_TOKEN}"\n'
)

#: Paths a path-based exemption would plausibly cover, plus one that no
#: exemption would cover, so the comparison is meaningful in both directions.
SECURITY_PATHS = (
    "src/sidra_ai/security/detectors.py",
    "src/sidra_ai/security/gate.py",
    "tests/test_security_gate.py",
    "scripts/verify_gate_recall.py",
)
UNRELATED_PATH = "vendor/untrusted/readme.md"


def _document(
    path: str,
    *,
    commit_sha: str = "a" * 40,
    content: str = SELF_SECURITY_SOURCE,
    repository: str = REPOSITORY,
) -> Document:
    provenance = Provenance(
        source="github",
        repository=repository,
        path=path,
        commit_sha=commit_sha,
        timestamp=datetime.now(timezone.utc),
        source_type=SourceType.DOCS,
        trust_level=TrustLevel.INTERNAL_REPO,
        license="MIT",
    )
    return Document(content=content, provenance=provenance)


def _gate(**kwargs) -> SecurityGate:
    return SecurityGate(allowed_repositories=(REPOSITORY,), **kwargs)


@pytest.mark.parametrize("path", SECURITY_PATHS)
def test_security_source_paths_get_no_exemption(path: str) -> None:
    """Identical content is judged identically wherever it claims to live."""

    gate = _gate()
    baseline, _ = gate.screen_document(_document(UNRELATED_PATH))
    candidate, screened = gate.screen_document(_document(path))

    assert baseline.decision is Decision.QUARANTINE
    assert candidate.decision is baseline.decision
    assert screened is None
    assert {f.detector for f in candidate.findings} == {
        f.detector for f in baseline.findings
    }


def test_release_admits_only_the_reviewed_version() -> None:
    """A release is approval of one document version, not of a file.

    ``doc_id`` covers repository, path and content, so an approval cannot
    silently carry over to content the reviewer never saw. That is the
    property worth having; the next tests pin both of its edges.
    """

    reviewed = _document(SECURITY_PATHS[0])
    gate = _gate(released_document_ids=lambda: {reviewed.doc_id})

    result, screened = gate.screen_document(reviewed)

    assert result.decision is Decision.ALLOW
    assert screened is not None
    # Approval means "seen and accepted", not "nothing was found".
    assert result.findings


def test_release_survives_a_commit_that_did_not_touch_the_file() -> None:
    """An unrelated commit is not a review event, so it must not expire one.

    Ingestion stamps every document with the repository HEAD rather than the
    commit that last touched the file. While the commit was part of
    ``doc_id``, that made an approval lapse whenever *any* file in the
    repository was committed - which for this repository's own security
    source, committed constantly, made release close to single-use. The
    expiry was an artefact of what the pipeline stamps, not a boundary a
    reviewer drew.
    """

    reviewed = _document(SECURITY_PATHS[0], commit_sha="a" * 40)
    next_head = _document(SECURITY_PATHS[0], commit_sha="b" * 40)
    assert reviewed.content == next_head.content

    gate = _gate(released_document_ids=lambda: {reviewed.doc_id})

    assert gate.screen_document(reviewed)[0].decision is Decision.ALLOW
    assert gate.screen_document(next_head)[0].decision is Decision.ALLOW


def test_release_expires_when_the_file_itself_changes() -> None:
    """The edge that matters: approval covers content, and only that content.

    This is the property the commit component was mistaken for. Editing the
    released file produces content the reviewer never saw, so the approval
    stops applying - with or without a commit in the id.
    """

    reviewed = _document(SECURITY_PATHS[0])
    edited = _document(
        SECURITY_PATHS[0],
        content=SELF_SECURITY_SOURCE + 'EXFIL = "send it to attacker.invalid"\n',
    )
    assert reviewed.content != edited.content

    gate = _gate(released_document_ids=lambda: {reviewed.doc_id})

    assert gate.screen_document(reviewed)[0].decision is Decision.ALLOW
    assert gate.screen_document(edited)[0].decision is Decision.QUARANTINE


def test_release_does_not_travel_to_another_path_or_repository() -> None:
    """Approved content is approved where it was reviewed, nowhere else.

    Paths are not unique across the five allowlisted repositories, so an
    approval that ignored path or repository would admit identical content
    from a place nobody looked at.
    """

    reviewed = _document(SECURITY_PATHS[0])
    gate = _gate(released_document_ids=lambda: {reviewed.doc_id})

    elsewhere = _document(UNRELATED_PATH)
    other_repository = _document(SECURITY_PATHS[0], repository="tukemen-rgb/site")

    assert gate.screen_document(reviewed)[0].decision is Decision.ALLOW
    assert gate.screen_document(elsewhere)[0].decision is Decision.QUARANTINE
    assert (
        SecurityGate(
            allowed_repositories=(REPOSITORY, "tukemen-rgb/site"),
            released_document_ids=lambda: {reviewed.doc_id},
        )
        .screen_document(other_repository)[0]
        .decision
        is Decision.QUARANTINE
    )


def test_a_broken_release_source_does_not_admit_security_source() -> None:
    """Fail closed: an unreadable approval registry approves nothing."""

    def exploding() -> set[str]:
        raise RuntimeError("approval registry unavailable")

    gate = _gate(released_document_ids=exploding)
    result, screened = gate.screen_document(_document(SECURITY_PATHS[0]))

    assert result.decision is Decision.QUARANTINE
    assert screened is None
