"""Two BLOCKs, one decision, two different disclosures.

An oversized payload and an unpermitted source are both ``BLOCK``. They are
not the same event at the audit boundary:

* the oversized one cleared the repository allowlist before its size was
  measured, so naming the repository repeats one of the operator's own
  configured entries;
* the unpermitted one *is* the allowlist refusing a value, so that value is
  precisely the untrusted thing and stays a length.

The rule is therefore keyed on whether the allowlist rejected, not on the
decision. These tests hold that distinction, because the easy mistakes both
collapse it: "BLOCK is BLOCK, drop everything" loses the attribution that
makes a size rejection actionable, and "it cleared the gate, name it" leaks
the identifier the gate refused.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

import pytest

from sidra_ai.documents import Document, Provenance, SourceType, TrustLevel
from sidra_ai.security.decisions import Decision, FindingCategory
from sidra_ai.security.gate import (
    GatePolicy,
    QuarantineStore,
    SecurityGate,
    _rejected_by_source_allowlist,
)

ALLOWED = "safe/repo"

# Credential-shaped values are generated by repetition so the repository
# never carries anything that looks live.
FAKE_TOKEN = "ghp_" + "B" * 24


def _provenance(repository: str = ALLOWED) -> Provenance:
    return Provenance(
        source="github",
        repository=repository,
        path="docs/plan.md",
        commit_sha="c" * 40,
        timestamp=datetime(2026, 8, 19, tzinfo=timezone.utc),
        source_type=SourceType.DOCS,
        trust_level=TrustLevel.INTERNAL_REPO,
        license="proprietary",
    )


def _gate(tmp_path, *, max_bytes: int = 512 * 1024) -> tuple[SecurityGate, QuarantineStore]:
    store = QuarantineStore(tmp_path / "quarantine.jsonl")
    gate = SecurityGate(
        GatePolicy(max_input_bytes=max_bytes),
        allowed_repositories=(ALLOWED,),
        quarantine_store=store,
    )
    return gate, store


def test_a_size_rejection_names_the_repository(tmp_path) -> None:
    gate, store = _gate(tmp_path, max_bytes=8)

    result, _ = gate.screen_document(
        Document(content="x" * 4096, provenance=_provenance())
    )

    assert result.decision is Decision.BLOCK
    audit = store.entries()[0]["provenance"]
    assert audit["source"] == "github"
    assert audit["repository"] == ALLOWED
    # The operator can now act on it: which repository, and why.
    assert result.finding_labels == ("oversized_input:byte_budget",)


def test_an_allowlist_rejection_names_nothing(tmp_path) -> None:
    """The refused identifier must not be written down by the refusal."""

    gate, store = _gate(tmp_path)
    rejected_repository = f"attacker/{FAKE_TOKEN}"

    result = gate.inspect(
        "body is never inspected after a source rejection",
        source="github",
        repository=rejected_repository,
        provenance=_provenance(rejected_repository),
    )

    assert result.decision is Decision.BLOCK
    entry = store.entries()[0]
    audit = entry["provenance"]
    assert "source" not in audit
    assert "repository" not in audit
    assert audit["repository_length"] == len(rejected_repository)

    serialized = json.dumps(entry, ensure_ascii=False)
    assert rejected_repository not in serialized
    assert FAKE_TOKEN not in serialized


def test_the_distinction_is_drawn_from_findings_not_from_the_decision(
    tmp_path,
) -> None:
    """Both are BLOCK, so the decision alone cannot tell them apart.

    If the rule is ever rewritten as ``decision is BLOCK``, one of these two
    behaviours silently becomes the other.
    """

    gate, store = _gate(tmp_path, max_bytes=8)

    oversized, _ = gate.screen_document(
        Document(content="y" * 4096, provenance=_provenance())
    )
    unpermitted = gate.inspect(
        "rejected", source="github", repository="attacker/elsewhere"
    )

    assert oversized.decision is unpermitted.decision is Decision.BLOCK
    assert not _rejected_by_source_allowlist(oversized)
    assert _rejected_by_source_allowlist(unpermitted)
    assert any(
        finding.category is FindingCategory.UNPERMITTED_SOURCE
        for finding in unpermitted.findings
    )


def test_uninspected_provenance_stays_a_length_on_an_attributed_block(
    tmp_path,
) -> None:
    """Naming the repository must not become naming everything.

    Path, URL, author, license, commit and extra are attacker-controlled and
    never pass through the secret/PII detectors, so widening the record to
    source and repository must leave them exactly as they were.
    """

    synthetic_pii = "oversize.person@example.com"
    provenance = Provenance(
        source="github",
        repository=ALLOWED,
        path=f"docs/{synthetic_pii}.md",
        commit_sha=FAKE_TOKEN,
        timestamp=datetime(2026, 8, 19, tzinfo=timezone.utc),
        source_type=SourceType.DOCS,
        trust_level=TrustLevel.INTERNAL_REPO,
        license=synthetic_pii,
        url=f"https://example.invalid/{FAKE_TOKEN}",
        author=synthetic_pii,
        extra={"note": FAKE_TOKEN},
    )
    gate, store = _gate(tmp_path, max_bytes=8)

    body = f"token={FAKE_TOKEN} contact={synthetic_pii}"
    result, screened = gate.screen_document(
        Document(content=body, provenance=provenance)
    )

    assert result.decision is Decision.BLOCK
    assert screened is None
    entry = store.entries()[0]
    assert entry["content"] is None
    assert entry["content_retention"] == "metadata_only"

    serialized = json.dumps(entry, ensure_ascii=False)
    for leaked in (
        FAKE_TOKEN,
        synthetic_pii,
        provenance.path,
        provenance.url,
        provenance.license,
        provenance.author,
        body,
    ):
        assert leaked not in serialized


@pytest.mark.parametrize("repository", ["SAFE/REPO", "Safe/Repo"])
def test_case_variants_of_an_allowlisted_repository_are_still_attributed(
    tmp_path, repository: str
) -> None:
    """The allowlist compares case-insensitively, so these cleared it.

    The persisted value is whatever provenance carried, which differs from
    the configured entry only in case - it is still the operator's own name
    for the repository and carries no attacker-chosen content.
    """

    gate, store = _gate(tmp_path, max_bytes=8)

    result, _ = gate.screen_document(
        Document(content="z" * 4096, provenance=_provenance(repository))
    )

    assert result.decision is Decision.BLOCK
    assert store.entries()[0]["provenance"]["repository"] == repository
